config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: "items#index"

  resources :items, only: [:new, :create, :show, :edit, :update,:destroy]do
    collection do
      get 'search'
    end
    resources :comments, only: [:create, :destroy]
  end
  resources :users, only: [:edit, :update, :show]do
  end
  resources :genres, only: [:new, :create, :edit, :update, :show]


end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :item
  belongs_to :user

  validates :price,    length: { in: 3..6 }, allow_nil: true	
  validates :text,    length: { maximum: 100 }
  validates :text_or_price, presence: true

  private
    def text_or_price
      text.presence or price.presence
    end
end

app/models/content.rb
class Content < ApplicationRecord

   
   mount_uploader :image, ImageUploader
end

app/models/genre.rb
class Genre < ApplicationRecord
  has_many :genre_items
  has_many :items, through: :genre_items
  validates :name, presence: true, uniqueness: true
end

app/models/genre_item.rb
class GenreItem < ApplicationRecord
  belongs_to :genre
  belongs_to :item
end

app/models/item.rb
class Item < ApplicationRecord
  mount_uploader :image, ImageUploader
  belongs_to :user
  has_many :comments, dependent: :delete_all
  has_many :genre_items
  has_many :genres, through: :genre_items

  validates :text,    length: { maximum: 200 }  

  def self.search(search)
    return Item.all unless search
    Item.where('name LIKE(?)', "%#{search}%")
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  
         has_many :items
         has_many :comments
        end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :authenticate_user!
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name])
  end

end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  def create
    comment = Comment.create(comment_params)
    redirect_to "/items/#{comment.item.id}"
  end

  def destroy
    comment = Comment.find(params[:id])
    comment.destroy
    redirect_to "/items/#{comment.item.id}"
  end

  private
  def comment_params
    params.require(:comment).permit(:text, :price).merge(user_id: current_user.id, item_id: params[:item_id])
  end

end

app/controllers/contents_controller.rb
class ContentsController < ApplicationController
  def index
    @contents = Content.all
    @genres = Genre.all
  end

  def new
    @contents = Content.new
  end

  def create
    Content.create(content_params)
  end

  private
  def content_params
    params.require(:content).permit(:name, :image, :text)
  end
end

app/controllers/genres_controller.rb
class GenresController < ApplicationController
  protect_from_forgery :except => [:create]

  def index
  end

  def new
    @genre = Genre.new
    # @genre.items << current_items
  end

  def create
    @genre = Genre.create(genre_params)
    if @genre.save
      redirect_to root_path, notice: 'ジャンルを作成しました'
    else
      render :new, fales: '失敗しました。'
    end
  end

  def edit
  
  end
    
  def update
    if @genre.update(genre_params)
      redirect_to genre_messages_path(@genre), notice: 'グループを編集しました'
    else
      render :edit
    end
  end

  def show
    @genre = Genre.find(params[:id])
    @items = @genre.items.order("created_at DESC")
    @genres = Genre.all
  end


  private
    def genre_params
      params.require(:genres).permit(:name)
    end

end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
  def index
    @items = Item.all.order("created_at DESC")
    @genres = Genre.all
  end

  def new
    @items = Item.new
  end

  def create
    Item.create(item_params)
  end

  def search
    @items = Item.search(params[:keyword])
    @genres = Genre.all
  end

  def show
    @items = Item.find(params[:id])
    @comment = Comment.new
    @comments = @items.comments.includes(:user).order("created_at DESC")
    @price = @items.comments.where.not(price: nil).average(:price)
    @max = @items.comments.where.not(price: nil).maximum(:price)
    @low = @items.comments.where.not(price: nil).minimum(:price)
    @count = @items.comments.where.not(text: nil).count
    @evaluation = @items.comments.where.not(price: nil).count
  end
  
  def destroy
    item = Item.find(params[:id])
    item.destroy
    
  end
  
  def edit
    @item = Item.find(params[:id])
  end

  def update
    item = Item.find(params[:id])
    item.update(item_params)
    redirect_to root_path
  end

  private
  def item_params
    params.require(:item).permit(:price, :name, :image, :size_w, :size_d, :size_h, :text,{genre_ids:[]}).merge(user_id: current_user.id)
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def show
    @user = User.find(params[:id])
    @items = @user.items.order("created_at DESC")
    @genres = Genre.all
  end

  def edit
  end

  def update
    if current_user.update(user_params)

      redirect_to root_path
    else
      render :edit
    end
  end

  private

  def user_params
    params.require(:user).permit(:name, :email)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/genres/edit.html.haml
.chat-group-form
  %h1 チャットグループ編集
  %form#edit_chat_group_22.edit_chat_group{"accept-charset" => "UTF-8", :action => "/chat_groups/22", :method => "post"}
    .chat-group-form__errors
      %h2
        1件のエラーが発生しました。
        %ul
          %li エラーです
    .chat-group-form__field.clearfix
      .chat-group-form__field--left
        %label.chat-group-form__label{for: "chat_group_name"} グループ名
      .chat-group-form__field--right
        %input#chat_group_name.chat-group-form__input{name: "chat_group[name]", placeholder: "グループ名を入力してください", type: "text", value: "ほげー"}/
    .chat-group-form__field.clearfix
      / この部分はインクリメンタルサーチ(ユーザー追加の非同期化)のときに使用します
    .chat-group-form__field.clearfix
      .chat-group-form__field--left
        %label.chat-group-form__label{for: "chat_group_チャットメンバー"} チャットメンバー
    .chat-group-form__field.clearfix
      .chat-group-form__field--left
      .chat-group-form__field--right
        / グループ作成機能の追加時はここにcollection_check_boxesの記述を入れてください
        / この部分はインクリメンタルサーチ(ユーザー追加の非同期化)のときにも使用します
        %input.chat-group-form__action-btn{"data-disable-with":"Save", name: "commit", type: "submit", value: "Save"}/

app/views/genres/new.html.haml
.top
  = render "shared/header"
.chat-group-form
  
  .chat-group-form_title
    Genre registration
  .chat-group-form_box_
    新規ジャンル登録
  %form#new_chat_group.new_chat_group{"accept-charset": "UTF-8", action: "/genres", method: "post"}
    %input{name: "utf8", type: "hidden", value: "✓"}/
    %input{name: "authenticity_token", type: "hidden", value: "AxFKlYEhD6eqX1PiZoTYQDANtKvgcFSXZQXHt5hyTl55/U/CHC5rtPavrcu2za65riz4tekZEy56vP6kEb2wYA=="}/
    .chat-group-form__field.clearfix
      .chat-group-form__field--left
        %label.chat-group-form__label{for: "genres_name"} ジャンル名
      .chat-group-form__field--right
        %input#chat_group_name.chat-group-form__input{name: "genres[name]", placeholder: "ジャンル名を入力してください", type: "text"}/
    .chat-group-form__field.clearfix
      / この部分はインクリメンタルサーチ（ユーザー追加の非同期化のときに使用します
    .chat-group-form__field.clearfix
      .chat-group-form__field--left
      .chat-group-form__field--right
        / グループ作成機能の追加時はここにcollection_check_boxesの記述を入れてください
        / この部分はインクリメンタルサーチ(ユーザー追加の非同期化)のときにも使用します
    .chat-group-form__field.clearfix
      .chat-group-form__field--left
      .chat-group-form__field--right
        %input.chat-group-form__action-btn{"data-disable-with":"Save", name: "commit", type: "submit", value: "Save"}/

app/views/genres/show.html.haml
.top
  = render "shared/header"

.main
  = render "shared/side_bar"
  .contents
    .contents_top
      .genre
        List :
        = @genre.name
    .item
      = render "shared/contents_main"
.contents_low
  .info
    information
  .icon
    = fa_icon 'facebook', class: 'icon'
    = fa_icon 'twitter', class: 'icon'
    = fa_icon 'google', class: 'icon'
    = fa_icon 'pinterest', class: 'icon'

app/views/items/create.html.haml
.body
  -# %script{:src => "js/jquery-3.4.1.min.js"}
  -# %script{:src => "js/iTyped.js"}

.top
  = render "shared/header"
.create-contents
  .create-contents_title
    Post complete
    -# %span#id_ityped.class_ityped
    .to_back
      = link_to root_path do
        Top

app/views/items/destroy.html.haml
.heder
  .heder_left
    .heder_left_name
      = link_to root_path do
        Make&Sell
  .heder_content
    %ul.heder_content_left
      %li.list
        = link_to current_user.name,  user_path(current_user.id)
        = fa_icon 'user-circle', class: 'icon'
.destroy
  削除が完了しました。
  = link_to root_path do
    Top

app/views/items/edit.html.haml
.top
  = render "shared/header"
  
.item_new
  .item_new__top
    Product edit
  .item_new_create
    .container
      = form_with(model: @item, local: true) do |form|
        .list
          .image
            = form.label :image,"商品画像" 
            = form.file_field :image, id: :item_image
            .image_in
              = image_tag @item.image.url if @item.image?
              :javascript
                $(function() {
                  function readURL(input) {
                    if (input.files && input.files[0]) {
                      var reader = new FileReader();
                      reader.onload = function (e) {
                        $('#image_prev').attr('src', e.target.result);
                      }
                      reader.readAsDataURL(input.files[0]);
                    }
                  }
                  $("#@items_image").change(function(){
                    readURL(this);
                  });
                });
          .name
            商品名：
            = form.text_field :name, placeholder: "Item name" , rows: "2"
          .price
            金額：
            = form.text_field :price, placeholder: "Item price"
          .size_w
            幅：
            = form.text_field :size_w, placeholder: "幅"
          .size_d
            奥行：
            = form.text_field :size_d, placeholder: "奥行"
          .size_h
            高さ：
            = form.text_field :size_h, placeholder: "高さ"
          .text
            紹介文：
            .input
              = form.text_area :text, placeholder: "紹介文を入力して下さい ※200文字以内", class: "input"
          .genre
            ジャンル：
            .genre_in
              = form.collection_check_boxes :genre_ids, Genre.all, :id, :name
          .btn
            = form.submit "SEND"
            

app/views/items/index.html.haml
.top
  = render "shared/header"

.main
  = render "shared/side_bar"
  .contents
    .contents_top
      .list
        Item list
    .contents_main
      .contents_main_box
        .contents_main_box__list
          - @items.each do |item|
            .contents_main_box__list__frame
              = link_to "/items/#{item.id}", method: :get do
                .contents_main_box__list__post{style:"background-image: url(#{item.image});"}

                .contents_main_box__list__text
                  .text
                    Item name :
                  .item_name
                    = item.name
                .price
                  Price
                  .price_in
                    ¥
                    = item.price.to_s(:delimited)
.contents_low
  .info
    information
  .icon
    = fa_icon 'facebook', class: 'icon'
    = fa_icon 'twitter', class: 'icon'
    = fa_icon 'google', class: 'icon'
    = fa_icon 'pinterest', class: 'icon'

app/views/items/new.html.haml
.top
  = render "shared/header"

.item_new
  .item_new__top
    Product registration
  .content
    = render "shared/item_new_create"

app/views/items/search.html.haml
.top
  = render "shared/header"
    
.main
  .side_search
    .info
      = form_with(url: search_items_path, local: true, method: :get, class: "search-form") do |form|
        = form.text_field :keyword, placeholder: "検索", class: "info"
        .search
          %button.search{type: "submit"}
            %i.icon
              = fa_icon 'search'
    .side_bar_box
      Category
      -@genres.each do |genre|
        .side_bar_list
          = genre.name
      
  .contents_search
    .search_top__list
      .search_top__list__box
        search results
      .search_top__icon
        = fa_icon 'bookmark', class: 'icon'
    .contents_main
      .contents_main_box
        .contents_main_box__list
          - @items.each do |item|
            .contents_main_box__list__a
              = link_to "/items/#{item.id}", method: :get do
                .contents_main_box__list__post{style:"background-image: url(#{item.image});"}

                .contents_main_box__list__text
                  Item name :
                  .item_name
                    = item.name
                .price
                  Price
                  .price_a
                    ¥
                    = item.price.to_s(:delimited)
.contents_low
  .info
    information
  .icon
    = fa_icon 'facebook', class: 'icon'
    = fa_icon 'twitter', class: 'icon'
    = fa_icon 'google', class: 'icon'
    = fa_icon 'pinterest', class: 'icon'
  

app/views/items/show.html.haml
.top
  = render "shared/header"

.show-contents
  .show-contents_title
    Details & Comment
  .show-contents_main
    .show-contents_main_in
      .show-contents_main_box
        .show-contents_main_box__list
          .show-contents_main_box__list__a
            .show-contents_main_box__list__post{style:"background-image: url(#{@items.image});"}
            .evaluation
              .evaluation_box
                .evaluation_box_text
                  現在の評価額
                -if @price.present? 
                  .evaluation_box_price
                    .evaluation_box_price__in
                      ¥
                      = @price.round.to_s(:delimited)
                - else
                  .evaluation_box_price_no
                    .evaluation_box_price_no__in
                      No comment
            .evaluation_max
              .evaluation_box
                .evaluation_box_text
                  コメント数 : 
                  .evaluation_box_text_in
                    = @count
                .evaluation_box_price
                  評価数 :
                  .evaluation_box_price__in
                    = @evaluation

          .show-contents_main_box__list__b
            .show-contents_main_box__list__text
              投稿者 :
              = @items.user.name
              さん
            .show-contents_main_box__list__text
              Item name :
              .item_name
                = @items.name
            .price
              .price_text
                Price (想定価格)
              .price_a
                ¥
                = @items.price.to_s(:delimited)
            .size
              Size :
              W
              = @items.size_w
              D
              = @items.size_d
              H
              = @items.size_h
            .sentence
              商品紹介 :
              -if current_user.id == @items.user_id
                .sentence_in
                  = simple_format(@items.text)
                .show_btn
                  .show_btn_in
                    .edit
                      = link_to '編集', "/items/#{@items.id}/edit", method: :get
                    .destroy
                      = link_to '削除', "/items/#{@items.id}", method: :delete
              - else
                .sentence_in
                  = simple_format(@items.text)

      .comment
        -if current_user
          = form_with(model: [@items, @comment], local: true) do |form|
            .comment_box
              .comment_box_text
                = form.text_field :text, placeholder: "コメントする", rows: "2", class: "comment_box_text_in"
              -if current_user.id == @items.user_id
                .comment_box_price
                  .comment_box_price_in_a
                    .text
                      ※投稿者の商品評価額は入力できません
                  .comment_box_btn
                    = form.submit "SEND", class: "btn"
              -else
                .comment_box_price
                  .comment_box_price_in
                    = form.text_field :price, placeholder: "評価額を入力して下さい ※半角入力", class: "comment_box_price_in"
                  .comment_box_btn
                    = form.submit "SEND", class: "btn"
              
    -if @comments.present? 
      .message
        .evaluation_list
          .evaluation_max
            .evaluation_box
              .evaluation_box_text
                .evaluation_box_text_in
                  Best price
              -if @max.present? 
                .evaluation_box_price
                  .evaluation_box_price__in
                  ¥
                  = @max.to_s(:delimited)
              - else
                .evaluation_box_price
                  .evaluation_box_price__in

          .evaluation_low
            .evaluation_box
              .evaluation_box_text
                .evaluation_box_text_in
                  Lowest price
              -if @low.present? 
                .evaluation_box_price
                  .evaluation_box_price__in
                  ¥
                  = @low.to_s(:delimited)
              - else
                .evaluation_box_price
                  .evaluation_box_price__in
      
        .message_in
          - @comments.each do |comment|
            .message_list
              .message_list_box
                %strong
                  -# user name :
                  = link_to comment.user.name, "/users/#{comment.user.id}"
              .message_list_box_low
                .message_list_box_in
                  .message_list_comment
                    comment
                  -if current_user.id == comment.user_id
                    .destroy_text
                    = link_to '✖︎', "/items/:item_id/comments/#{comment.id}", method: :delete
                .message_list_in_text
                  = comment.text
                -if comment.price.present? 
                  .message_list_price
                    評価額は
                    .message_list_price_in
                      ¥
                      = comment.price.to_s(:delimited)
                  

  .show-icon
    = fa_icon 'facebook', class: 'icon'
    = fa_icon 'twitter', class: 'icon'
    = fa_icon 'google', class: 'icon'
    = fa_icon 'pinterest', class: 'icon'

app/views/items/update.html.haml
.heder
  .heder_left
    .heder_left_name
      = link_to root_path do
        Make&Sell
  .heder_content
    %ul.heder_content_left
      %li.list
        = link_to current_user.name,  user_path(current_user.id)
        = fa_icon 'user-circle', class: 'icon'

.update
  編集が完了しました。
  = link_to root_path do
    Top

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %title Makeandsell
    = csrf_meta_tags
    = csp_meta_tag
    %script{:src => "https://code.jquery.com/jquery-2.2.4.min.js"}
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_include_tag 'application', 'data-turbolinks-track': 'reload'
  %body
    = yield

app/views/shared/_contents_main.html.haml
.contents_main
  .contents_main_box
    .contents_main_box__list
      - @items.each do |item|
        .contents_main_box__list__frame
          = link_to "/items/#{item.id}", method: :get do
            .contents_main_box__list__post{style:"background-image: url(#{item.image});"}

            .contents_main_box__list__text
              .text
                Item name :
              .item_name
                = item.name
            .price
              Price
              .price_in
                ¥
                = item.price.to_s(:delimited)

app/views/shared/_header.html.haml
.heder
  .heder_left
    .heder_left_name
      = link_to root_path do
        Make&Sell
  .heder_content
    .heder_content_left
      .list
        = link_to current_user.name,  user_path(current_user.id)
        = fa_icon 'user-circle', class: 'icon'
    .heder_content_left
      .list
        = link_to new_item_path do
          item 
          = fa_icon 'image', class: 'icon'
    .heder_content_center
      .list
        = link_to new_genre_path do
          genre
          = fa_icon 'leaf', class: 'icon'
    .heder_content_right
      .list
        = link_to edit_user_path(current_user) do
          User edit
          = fa_icon 'id-badge', class: 'icon'

app/views/shared/_item_new_create.html.haml
.item_new_create
  .container
    = form_with(model: @items,method: :post, local: true) do |form|
      .list
        .image
          = form.label :image,"商品画像" 
          = form.file_field :image, id: :item_image
          .image_in
            = image_tag @items.image.url, id: :image_prev if @items.image?
            :javascript
              $(function() {
                function readURL(input) {
                  if (input.files && input.files[0]) {
                    var reader = new FileReader();
                    reader.onload = function (e) {
                      $('#image_prev').attr('src', e.target.result);
                    }
                    reader.readAsDataURL(input.files[0]);
                  }
                }
                $("#@items_image").change(function(){
                  readURL(this);
                });
              });

        .name
          商品名：
          = form.text_field :name, placeholder: "Item name" , rows: "2"
        .price
          金額：
          = form.text_field :price, placeholder: "Item price"
        .size_w
          幅：
          = form.text_field :size_w, placeholder: "幅"
        .size_d
          奥行：
          = form.text_field :size_d, placeholder: "奥行"
        .size_h
          高さ：
          = form.text_field :size_h, placeholder: "高さ"
        .text
          紹介文：
          .input
            = form.text_area :text, placeholder: "紹介文を入力して下さい ※200文字以内", class: "input"
        .genre
          ジャンル：
          .genre_in
            = form.collection_check_boxes :genre_ids, Genre.all, :id, :name
        .btn
          = form.submit "SEND"

app/views/shared/_side_bar.html.haml
.side_bar
  .info
    = form_with(url: search_items_path, local: true, method: :get, class: "search-form") do |form|
      = form.text_field :keyword, placeholder: "検索", class: "info"
      .search
        %button.search{type: "submit"}
          %i.icon
            = fa_icon 'search'
  .side_bar_box
    Category
    -@genres.each do |genre|
      .side_bar_list
        = link_to genre.name, "/genres/#{genre.id}"

app/views/users/edit.html.haml
#account-page.account-page
  .account-page__inner.clearfix
    .account-page__inner--left.account-page__header
      .top
        %h2 Edit Account
        .list
          %h5 アカウントの編集
          .log
            .log_box
              = link_to "ログアウト", destroy_user_session_path, method: :delete, class: 'btn'
            .log_box
              = link_to "TOPに戻る", root_path, class: 'btn'
    .account-page__inner--right.user-form
      = form_for(current_user) do |f|
        .field
          .field-label
            = f.label :name
          .field-input
            = f.text_field :name, autofocus: true
        .field
          .field-label
            = f.label :email
          .field-input
            = f.email_field :email
        .actions
          .btn
            = f.submit "Update", class: 'btn'

app/views/users/show.html.haml
.top
  = render "shared/header"

.main
  = render "shared/side_bar"
        
  .contents_show
    .mypage
      .mypage_top
        -# = "My page: #{@user.name}"
        = @user.name
      .mypage_icon
        = fa_icon 'user-circle', class: 'icon'

    .contents_main
      .contents_main_box
        .contents_main_box__list
          - @items.each do |items|
            .contents_main_box__list__a
              = link_to item_path(items.id) do
                .contents_main_box__list__post{style:"background-image: url(#{items.image});"}

                .contents_main_box__list__text
                  Item name :
                  .item_name
                    = items.name
                .price
                  Price
                  .price_a
                    ¥
                    = items.price.to_s(:delimited)
.contents_low
  .info
    information
  .icon
    = fa_icon 'facebook', class: 'icon'
    = fa_icon 'twitter', class: 'icon'
    = fa_icon 'google', class: 'icon'
    = fa_icon 'pinterest', class: 'icon'
  